# Generated by Django 3.0.5 on 2020-04-19 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_listingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='created_at',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='listing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
