# Generated by Django 3.0.5 on 2020-04-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200419_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('0', 'No'), ('1', 'Yes')], max_length=10)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_extras', to='listings.Listing')),
            ],
        ),
    ]
