# Generated by Django 3.0.5 on 2020-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
