# Generated by Django 3.0.5 on 2020-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
